# Generated by Django 4.0 on 2022-02-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0012_rename_statusf_order_status_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status_changed',
            new_name='status',
        ),
    ]
